# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\create_object.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateObject(object):
    def setupUi(self, CreateObject):
        CreateObject.setObjectName("CreateObject")
        CreateObject.resize(400, 358)
        self.label = QtWidgets.QLabel(CreateObject)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CreateObject)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.name_edit = QtWidgets.QLineEdit(CreateObject)
        self.name_edit.setGeometry(QtCore.QRect(10, 40, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.name_edit.setFont(font)
        self.name_edit.setText("")
        self.name_edit.setObjectName("name_edit")
        self.description_edit = QtWidgets.QTextEdit(CreateObject)
        self.description_edit.setGeometry(QtCore.QRect(10, 120, 381, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.description_edit.setFont(font)
        self.description_edit.setObjectName("description_edit")
        self.ok_cancel_button_box = QtWidgets.QDialogButtonBox(CreateObject)
        self.ok_cancel_button_box.setGeometry(QtCore.QRect(10, 320, 191, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.ok_cancel_button_box.setFont(font)
        self.ok_cancel_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok_cancel_button_box.setObjectName("ok_cancel_button_box")

        self.retranslateUi(CreateObject)
        QtCore.QMetaObject.connectSlotsByName(CreateObject)

    def retranslateUi(self, CreateObject):
        _translate = QtCore.QCoreApplication.translate
        CreateObject.setWindowTitle(_translate("CreateObject", "Create object"))
        self.label.setText(_translate("CreateObject", "Object name:"))
        self.label_2.setText(_translate("CreateObject", "Object description:"))
        self.description_edit.setHtml(_translate("CreateObject", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateObject = QtWidgets.QWidget()
    ui = Ui_CreateObject()
    ui.setupUi(CreateObject)
    CreateObject.show()
    sys.exit(app.exec_())
