# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\invite_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvitesList(object):
    def setupUi(self, InvitesList):
        InvitesList.setObjectName("InvitesList")
        InvitesList.resize(411, 313)
        self.invite_list_wiget = QtWidgets.QListWidget(InvitesList)
        self.invite_list_wiget.setGeometry(QtCore.QRect(10, 10, 391, 251))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.invite_list_wiget.setFont(font)
        self.invite_list_wiget.setObjectName("invite_list_wiget")
        self.accept_button = QtWidgets.QPushButton(InvitesList)
        self.accept_button.setGeometry(QtCore.QRect(10, 270, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.accept_button.setFont(font)
        self.accept_button.setObjectName("accept_button")
        self.reject_button = QtWidgets.QPushButton(InvitesList)
        self.reject_button.setGeometry(QtCore.QRect(110, 270, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.reject_button.setFont(font)
        self.reject_button.setObjectName("reject_button")
        self.cancel_button = QtWidgets.QPushButton(InvitesList)
        self.cancel_button.setGeometry(QtCore.QRect(310, 270, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.update_button = QtWidgets.QPushButton(InvitesList)
        self.update_button.setGeometry(QtCore.QRect(210, 270, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.update_button.setFont(font)
        self.update_button.setObjectName("update_button")

        self.retranslateUi(InvitesList)
        QtCore.QMetaObject.connectSlotsByName(InvitesList)

    def retranslateUi(self, InvitesList):
        _translate = QtCore.QCoreApplication.translate
        InvitesList.setWindowTitle(_translate("InvitesList", "Invites"))
        self.accept_button.setText(_translate("InvitesList", "Accept"))
        self.reject_button.setText(_translate("InvitesList", "Reject"))
        self.cancel_button.setText(_translate("InvitesList", "Cancel"))
        self.update_button.setText(_translate("InvitesList", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InvitesList = QtWidgets.QWidget()
    ui = Ui_InvitesList()
    ui.setupUi(InvitesList)
    InvitesList.show()
    sys.exit(app.exec_())
