# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\object_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ObjectList(object):
    def setupUi(self, ObjectList):
        ObjectList.setObjectName("ObjectList")
        ObjectList.resize(520, 595)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ObjectList)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(ObjectList)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.update_btn = QtWidgets.QPushButton(ObjectList)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.update_btn.setFont(font)
        self.update_btn.setObjectName("update_btn")
        self.verticalLayout_3.addWidget(self.update_btn)
        self.link_btn = QtWidgets.QPushButton(ObjectList)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.link_btn.setFont(font)
        self.link_btn.setCheckable(False)
        self.link_btn.setAutoRepeat(False)
        self.link_btn.setAutoDefault(False)
        self.link_btn.setDefault(False)
        self.link_btn.setFlat(False)
        self.link_btn.setObjectName("link_btn")
        self.verticalLayout_3.addWidget(self.link_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.object_list_widget = QtWidgets.QListWidget(ObjectList)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.object_list_widget.setFont(font)
        self.object_list_widget.setObjectName("object_list_widget")
        self.horizontalLayout_6.addWidget(self.object_list_widget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)

        self.retranslateUi(ObjectList)
        QtCore.QMetaObject.connectSlotsByName(ObjectList)

    def retranslateUi(self, ObjectList):
        _translate = QtCore.QCoreApplication.translate
        ObjectList.setWindowTitle(_translate("ObjectList", "Objects"))
        self.username_label.setText(_translate("ObjectList", "123"))
        self.update_btn.setText(_translate("ObjectList", "Update"))
        self.link_btn.setText(_translate("ObjectList", "Link"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ObjectList = QtWidgets.QWidget()
    ui = Ui_ObjectList()
    ui.setupUi(ObjectList)
    ObjectList.show()
    sys.exit(app.exec_())
