# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\user_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserList(object):
    def setupUi(self, UserList):
        UserList.setObjectName("UserList")
        UserList.resize(400, 310)
        self.user_list_widget = QtWidgets.QListWidget(UserList)
        self.user_list_widget.setGeometry(QtCore.QRect(10, 10, 381, 251))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.user_list_widget.setFont(font)
        self.user_list_widget.setObjectName("user_list_widget")
        self.invite_button = QtWidgets.QPushButton(UserList)
        self.invite_button.setGeometry(QtCore.QRect(10, 270, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.invite_button.setFont(font)
        self.invite_button.setObjectName("invite_button")
        self.cancel_button = QtWidgets.QPushButton(UserList)
        self.cancel_button.setGeometry(QtCore.QRect(110, 270, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.update_button = QtWidgets.QPushButton(UserList)
        self.update_button.setGeometry(QtCore.QRect(300, 270, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.update_button.setFont(font)
        self.update_button.setObjectName("update_button")

        self.retranslateUi(UserList)
        QtCore.QMetaObject.connectSlotsByName(UserList)

    def retranslateUi(self, UserList):
        _translate = QtCore.QCoreApplication.translate
        UserList.setWindowTitle(_translate("UserList", "Users"))
        self.invite_button.setText(_translate("UserList", "Invite"))
        self.cancel_button.setText(_translate("UserList", "Cancel"))
        self.update_button.setText(_translate("UserList", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserList = QtWidgets.QWidget()
    ui = Ui_UserList()
    ui.setupUi(UserList)
    UserList.show()
    sys.exit(app.exec_())
